package model

/**
 * Created by root on 15-9-29.
 */
class CTData {
  val CONTRACTID: String = ""
  val TDATETIME: String = ""
  val CONTRACTNAME: String = ""
  val LASTPX: String = ""
  val HIGHPX: String = ""
  val LOWPX: String = ""
  val CQ: String = ""
  val TQ: String = ""
  val LASTQTY: String = ""
  val INITOPENINTS: String = ""
  val OPENINTS: String = ""
  val INTSCHG: String = ""
  val TURNOVER: String = ""
  val RISELIMIT: String = ""
  val FALLLIMIT: String = ""
  val PRESETTLE: String = ""
  val PRECLOSE: String = ""
  val OPENPX: String = ""
  val CLOSEPX: String = ""
  val SETTLEMENTPX: String = ""
  val LIFELOW: String = ""
  val LIFEHIGH: String = ""
  val AVGPX: String = ""
  val BIDIMPLYQTY: String = ""
  val ASKIMPLYQTY: String = ""
  val SIDE: String = ""
  val S1: String = ""
  val B1: String = ""
  val SV1: String = ""
  val BV1: String = ""
  val S5: String = ""
  val S4: String = ""
  val S3: String = ""
  val S2: String = ""
  val B2: String = ""
  val B3: String = ""
  val B4: String = ""
  val B5: String = ""
  val SV5: String = ""
  val SV4: String = ""
  val SV3: String = ""
  val SV2: String = ""
  val BV2: String = ""
  val BV3: String = ""
  val BV4: String = ""
  val BV5: String = ""
  val PREDELTA: String = ""
  val CURRDELTA: String = ""
  val CHG: String = ""
  val CHGPCT: String = ""
  val VARIETIES: String = ""
  val LOCALTIME: String = ""
  val MFLXID: String = ""
  val MARKET: String = ""
  val UNIX: String = ""

}
